FutureSynchronyzer: thread::FutureSynchronyzer< ResultPolicy, FutureFactory, OutputResult > Class Template Reference
thread::FutureSynchronyzer< ResultPolicy, FutureFactory, OutputResult > Class Template Reference
#include <FutureSynchronyzer.hxx>
Public Member Functions
FutureSynchronyzer (OutputResult *outputResult=NULL, size_t numThreads=std::thread::hardware_concurrency() > 0?std::thread::hardware_concurrency():1)
virtual ~FutureSynchronyzer ()
template<typename Fn , typename... Args>
void addFunction (Fn &&function, Args &&...args)
void launch ()
void wait ()
void launchAndWait ()
OutputResult * outputResult () const
size_t numThreads () const
Private Member Functions
std::function< OutputResult()> getNextFunction ()
template<typename Output = OutputResult, typename Policy = ResultPolicy>
std::enable_if<!(std::is_same< Output, void >::value)&&!(std::is_same< Policy, policy::NoResultPolicy >::value), void >::type applyResult (std::future< Output > &f)
template<typename Output = OutputResult, typename Policy = ResultPolicy>
std::enable_if<(std::is_same< Output, void >::value)||(std::is_same< Policy, policy::NoResultPolicy >::value), void >::type applyResult (std::future< Output > &f)
Private Attributes
std::vector< std::future< OutputResult > > m_futures
std::vector< std::function< OutputResult()> > m_functions
size_t m_numThreads
OutputResult * m_outputResult
Detailed Description
template<class ResultPolicy = policy::NoResultPolicy, class FutureFactory = factory::AsyncFutureFactory, typename OutputResult = void>
class thread::FutureSynchronyzer< ResultPolicy, FutureFactory, OutputResult >
This class permits to add functions and it's arguments and launch them with a limit number of threads defined at the onbject's construction. All the function added must returned the same type of argument.
Constructor & Destructor Documentation
template<class ResultPolicy = policy::NoResultPolicy, class FutureFactory = factory::AsyncFutureFactory, typename OutputResult = void> thread::FutureSynchronyzer< ResultPolicy, FutureFactory, OutputResult >::FutureSynchronyzer (OutputResult * outputResult = NULL, size_t numThreads = std::thread::hardware_concurrency(), 0?std::thread::hardware_concurrency():1) inline
Construct the Future Synchronizer.
Parameters
outputResult the return result (optional);
numThreads the max number of threads. By default, the number of concurrent threads supported if detected or 1.
template<class ResultPolicy = policy::NoResultPolicy, class FutureFactory = factory::AsyncFutureFactory, typename OutputResult = void> virtual thread::FutureSynchronyzer< ResultPolicy, FutureFactory, OutputResult >::~FutureSynchronyzer () inline virtual
Member Function Documentation
template<class ResultPolicy = policy::NoResultPolicy, class FutureFactory = factory::AsyncFutureFactory, typename OutputResult = void> template<typename Fn , typename... Args> void thread::FutureSynchronyzer< ResultPolicy, FutureFactory, OutputResult >::addFunction (Fn && function, Args &&... args) inline
Add the function and its arguments to the list of function
Parameters
function
args all arguments
template<class ResultPolicy = policy::NoResultPolicy, class FutureFactory = factory::AsyncFutureFactory, typename OutputResult = void> template<typename Output = OutputResult, typename Policy = ResultPolicy> std::enable_if<!(std::is_same<Output, void>::value) && !(std::is_same<Policy, policy::NoResultPolicy>::value), void>::type thread::FutureSynchronyzer< ResultPolicy, FutureFactory, OutputResult >::applyResult (std::future< Output > & f) inline private
Launch the result operation. This method is used if OutputResult is not void and ResultPolicy is not ResultPolicy.
Parameters
f the finished future with the result
Referenced by thread::FutureSynchronyzer< ResultPolicy, FutureFactory, OutputResult >::launch(), and thread::FutureSynchronyzer< ResultPolicy, FutureFactory, OutputResult >::wait().
template<class ResultPolicy = policy::NoResultPolicy, class FutureFactory = factory::AsyncFutureFactory, typename OutputResult = void> template<typename Output = OutputResult, typename Policy = ResultPolicy> std::enable_if<(std::is_same<Output, void>::value) || (std::is_same<Policy, policy::NoResultPolicy>::value), void>::type thread::FutureSynchronyzer< ResultPolicy, FutureFactory, OutputResult >::applyResult (std::future< Output > & f) inline private
Launch the result operation. This method is used if OutputResult is void or ResultPolicy is ResultPolicy.
Parameters
f the finished future with the result
template<class ResultPolicy = policy::NoResultPolicy, class FutureFactory = factory::AsyncFutureFactory, typename OutputResult = void> std::function<OutputResult()> thread::FutureSynchronyzer< ResultPolicy, FutureFactory, OutputResult >::getNextFunction () inline private
Returns
the next function to be treated.
Referenced by thread::FutureSynchronyzer< ResultPolicy, FutureFactory, OutputResult >::launch().
template<class ResultPolicy = policy::NoResultPolicy, class FutureFactory = factory::AsyncFutureFactory, typename OutputResult = void> void thread::FutureSynchronyzer< ResultPolicy, FutureFactory, OutputResult >::launch () inline
Launch all functions
References thread::FutureSynchronyzer< ResultPolicy, FutureFactory, OutputResult >::applyResult(), thread::FutureSynchronyzer< ResultPolicy, FutureFactory, OutputResult >::getNextFunction(), and thread::FutureSynchronyzer< ResultPolicy, FutureFactory, OutputResult >::m_numThreads.
Referenced by thread::FutureSynchronyzer< ResultPolicy, FutureFactory, OutputResult >::launchAndWait().
template<class ResultPolicy = policy::NoResultPolicy, class FutureFactory = factory::AsyncFutureFactory, typename OutputResult = void> void thread::FutureSynchronyzer< ResultPolicy, FutureFactory, OutputResult >::launchAndWait () inline
Launch all the functions and wait them to be finished.
References thread::FutureSynchronyzer< ResultPolicy, FutureFactory, OutputResult >::launch(), and thread::FutureSynchronyzer< ResultPolicy, FutureFactory, OutputResult >::wait().
template<class ResultPolicy = policy::NoResultPolicy, class FutureFactory = factory::AsyncFutureFactory, typename OutputResult = void> size_t thread::FutureSynchronyzer< ResultPolicy, FutureFactory, OutputResult >::numThreads () const inline
References thread::FutureSynchronyzer< ResultPolicy, FutureFactory, OutputResult >::m_numThreads.
template<class ResultPolicy = policy::NoResultPolicy, class FutureFactory = factory::AsyncFutureFactory, typename OutputResult = void> OutputResult* thread::FutureSynchronyzer< ResultPolicy, FutureFactory, OutputResult >::outputResult () const inline
References thread::FutureSynchronyzer< ResultPolicy, FutureFactory, OutputResult >::m_outputResult.
template<class ResultPolicy = policy::NoResultPolicy, class FutureFactory = factory::AsyncFutureFactory, typename OutputResult = void> void thread::FutureSynchronyzer< ResultPolicy, FutureFactory, OutputResult >::wait () inline
Wait all functions to be finished.
References thread::FutureSynchronyzer< ResultPolicy, FutureFactory, OutputResult >::applyResult().
Referenced by thread::FutureSynchronyzer< ResultPolicy, FutureFactory, OutputResult >::launchAndWait().
Member Data Documentation
template<class ResultPolicy = policy::NoResultPolicy, class FutureFactory = factory::AsyncFutureFactory, typename OutputResult = void> std::vector<std::function<OutputResult()> > thread::FutureSynchronyzer< ResultPolicy, FutureFactory, OutputResult >::m_functions private
template<class ResultPolicy = policy::NoResultPolicy, class FutureFactory = factory::AsyncFutureFactory, typename OutputResult = void> std::vector<std::future<OutputResult> > thread::FutureSynchronyzer< ResultPolicy, FutureFactory, OutputResult >::m_futures private
template<class ResultPolicy = policy::NoResultPolicy, class FutureFactory = factory::AsyncFutureFactory, typename OutputResult = void> size_t thread::FutureSynchronyzer< ResultPolicy, FutureFactory, OutputResult >::m_numThreads private
Referenced by thread::FutureSynchronyzer< ResultPolicy, FutureFactory, OutputResult >::launch(), and thread::FutureSynchronyzer< ResultPolicy, FutureFactory, OutputResult >::numThreads().
template<class ResultPolicy = policy::NoResultPolicy, class FutureFactory = factory::AsyncFutureFactory, typename OutputResult = void> OutputResult* thread::FutureSynchronyzer< ResultPolicy, FutureFactory, OutputResult >::m_outputResult private
Referenced by thread::FutureSynchronyzer< ResultPolicy, FutureFactory, OutputResult >::outputResult().
The documentation for this class was generated from the following file:
FutureSynchronyzer.hxx